name: "Generar mi proyecto"
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - name: dependencias
        run: npm install
      - name: test
        run: npm test
